(()=>{'use strict';
const $=id=>document.getElementById(id);const state={ws:null,symbol:'1HZ90V',prices:[],digits:Array(10).fill(0),stake:.25,contract:'EVENODD',activeSide:null,auto:true,pending:null,balance:10000,net:0,wins:0,losses:0,reconnect:null};
const ui={price:$('price'),change:$('change'),chart:$('chart'),digits:$('digits'),conn:$('connection'),ticks:$('ticks'),pnl:$('pnl'),record:$('record'),left:$('leftTrade'),stop:$('stopTrade')};
function toast(s){const e=$('toast');e.textContent=s;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
function fmt(n){return Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function lastDigit(q){const s=String(q);const dec=(s.split('.')[1]||'');return Number(dec.length?dec.at(-1):String(Math.trunc(q)).at(-1))}
function setConn(t,ok=false){ui.conn.textContent='● '+t;ui.conn.style.color=ok?'#16e79a':'#e0bd00'}
function renderDigits(){const total=state.digits.reduce((a,b)=>a+b,0);if(!total)return;const p=state.digits.map(v=>v/total*100);let hi=0,lo=0;for(let i=1;i<10;i++){if(p[i]>p[hi])hi=i;if(p[i]<p[lo])lo=i}ui.digits.innerHTML=p.map((v,i)=>`<div class="digit ${i===lo?'red':i===hi?'green':''}"><b>${i}</b><small>${v.toFixed(1)}%</small><div class="bar"></div></div>`).join('')}
function draw(){const c=ui.chart,x=c.getContext('2d'),d=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;if(!w||!h)return;c.width=w*d;c.height=h*d;x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);x.strokeStyle='#17366f';x.lineWidth=1;for(let i=0;i<10;i++){const yy=i*h/10;x.beginPath();x.moveTo(0,yy);x.lineTo(w,yy);x.stroke()}const p=state.prices.slice(-90);if(p.length<2)return;const min=Math.min(...p),max=Math.max(...p),r=max-min||1;x.beginPath();p.forEach((v,i)=>{const xx=i*(w-12)/(p.length-1)+6,yy=h-20-(v-min)/r*(h-40);i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.strokeStyle='#f4f7ff';x.lineWidth=2;x.stroke();$('high').textContent=fmt(max);$('mid').textContent=fmt((max+min)/2);$('low').textContent=fmt(min)}
function update(){const q=state.prices.at(-1);if(q==null)return;ui.price.textContent=fmt(q);if(state.prices.length>1){const base=state.prices[0];ui.change.textContent=(q>=base?'↑ ':'↓ ')+Math.abs((q-base)/base*100).toFixed(2)+'%';ui.change.style.color=q>=base?'#12e89a':'#ff3a5f'}$('marketName').textContent=$('market').selectedOptions[0].textContent.replace(' Index','');$('ticks').textContent=state.prices.length+' ticks';renderDigits();draw();}
function request(ws){ws.send(JSON.stringify({ticks:state.symbol,subscribe:1,req_id:1}));ws.send(JSON.stringify({ticks_history:state.symbol,count:100,end:'latest',style:'ticks',subscribe:0,req_id:2}));}
function connect(){clearTimeout(state.reconnect);setConn('Connecting…');const ws=new WebSocket('wss://ws.binaryws.com/websockets/v3');state.ws=ws;ws.onopen=()=>{setConn('Live market connected',true);request(ws)};ws.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.error){setConn(d.error.message||'Deriv error');return}if(d.msg_type==='history')load(d.history?.prices||[]);if(d.msg_type==='tick')tick(d.tick.quote)}catch(err){}};ws.onclose=()=>{setConn('Reconnecting…');state.reconnect=setTimeout(connect,2500)};ws.onerror=()=>setConn('Connection error')}
function load(a){state.prices=a.map(Number).filter(Number.isFinite).slice(-100);state.digits=Array(10).fill(0);state.prices.forEach(q=>state.digits[lastDigit(q)]++);update()}
function tick(q){q=Number(q);if(!Number.isFinite(q))return;state.prices.push(q);if(state.prices.length>120)state.prices.shift();state.digits[lastDigit(q)]++;if(state.pending)settle(q);if(state.activeSide&&state.auto&&!state.pending)place(state.activeSide);update()}
function setStake(v){state.stake=Math.max(.25,Math.min(100,Math.round(v*100)/100));$('stake').textContent=state.stake.toFixed(2)}
function label(side){if(state.contract==='EVENODD')return side==='left'?'Even':'Odd';if(state.contract==='OVERUNDER')return side==='left'?'Over':'Under';if(state.contract==='RISEFALL')return side==='left'?'Rise':'Fall';return side==='left'?'Match':'Differ'}
function resetLeft(){ui.left.className='even';ui.left.innerHTML=`${label('left')} <small><span id="quote">50.49</span></small><em>Payout <span id="payout">98.23%</span></em>`}
function place(side){if(state.pending||state.balance<state.stake)return;state.balance-=state.stake;state.pending={side,entry:state.prices.at(-1),stake:state.stake,contract:state.contract};ui.left.textContent='STOP';ui.left.className='stop';toast(label(side)+' demo trade started')}
function settle(q){const t=state.pending;if(!t)return;const d=lastDigit(q);let win=false;if(t.contract==='EVENODD')win=t.side==='left'?d%2===0:d%2===1;else if(t.contract==='OVERUNDER')win=t.side==='left'?d>=4:d<=3;else if(t.contract==='RISEFALL')win=t.side==='left'?q>t.entry:q<t.entry;state.pending=null;const payout=win?t.stake*1.9823:0;state.net+=win?payout-t.stake:-t.stake;state.balance+=payout;if(win)state.wins++;else state.losses++;ui.pnl.textContent=(state.net>=0?'+$':'-$')+Math.abs(state.net).toFixed(2);ui.record.textContent=`77 - ${state.wins}W - ${state.losses}L`;toast(win?'WIN +$'+(payout-t.stake).toFixed(2):'LOSS -$'+t.stake.toFixed(2));if(state.activeSide&&state.auto)place(state.activeSide)}
function stop(){state.activeSide=null;state.auto=false;state.pending=null;resetLeft();toast('Trading stopped')}
ui.left.onclick=()=>{if(state.activeSide){stop();return}state.activeSide='left';state.auto=true;place('left')};ui.stopTrade.onclick=()=>stop();$('market').onchange=()=>{state.symbol=$('market').value;state.prices=[];state.digits=Array(10).fill(0);try{state.ws.close()}catch{}connect()};document.querySelectorAll('.contract-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.contract-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.contract=b.dataset.contract;stop();});$('stakeMinus').onclick=()=>setStake(state.stake-.25);$('stakePlus').onclick=()=>setStake(state.stake+.25);document.querySelectorAll('[data-stake]').forEach(b=>b.onclick=()=>setStake(+b.dataset.stake));$('auto').onclick=()=>{state.auto=true;$('auto').classList.add('active');$('manual').classList.remove('active')};$('manual').onclick=()=>{state.auto=false;$('manual').classList.add('active');$('auto').classList.remove('active')};window.addEventListener('resize',draw);setStake(.25);connect();
})();
