(() => {
'use strict';
const $=id=>document.getElementById(id);
const state={ws:null,symbol:'1HZ90V',prices:[],digits:Array(10).fill(0),stake:.25,contract:'EVENODD',mode:'AUTO',balance:10000,net:0,wins:0,losses:0,pending:null,stopped:false,reconnect:null,tickSerial:77};
const ui={grid:$('digitGrid'),price:$('price'),change:$('change'),marketName:$('marketName'),canvas:$('chartCanvas'),connection:$('connection'),tickCount:$('tickCount'),stake:$('stake'),net:$('sessionNet'),session:$('sessionCount'),even:$('evenAction'),odd:$('oddAction'),target:$('targetProfit'),loss:$('stopLoss'),mult:$('multiplier'),scale1:$('scale1'),scale2:$('scale2'),scale3:$('scale3'),scale4:$('scale4')};
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),1800)}
function fmt(n){return Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function lastDigit(q){const s=String(q);const m=s.replace(/\D/g,'');return m?Number(m.at(-1)):null}
function setConn(t,ok=false){ui.connection.textContent='● '+t;ui.connection.style.color=ok?'#08e39b':'#f0ca17'}
function currentLabel(){if(state.contract==='OVERUNDER')return state.lastSide==='right'?'UNDER':'OVER';if(state.contract==='MATCHES')return 'MATCH';return state.lastSide==='right'?'ODD':'EVEN'}
function updateDigits(){const total=state.digits.reduce((a,b)=>a+b,0);if(!total)return;const p=state.digits.map(v=>v/total*100);let hi=0;for(let i=1;i<10;i++)if(p[i]>p[hi])hi=i;let lo=hi===0?1:0;for(let i=0;i<10;i++){if(i!==hi&&p[i]<p[lo])lo=i}ui.grid.innerHTML=p.map((v,i)=>`<div class="digit ${i===hi?'green':''} ${i===lo?'red':''}"><b>${i}</b><small>${v.toFixed(1)}%</small></div>`).join('')}
function drawChart(){const c=ui.canvas,ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;if(!w||!h)return;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const p=state.prices.slice(-90);if(p.length<2)return;const min=Math.min(...p),max=Math.max(...p),r=max-min||1;ctx.strokeStyle='#183b70';ctx.lineWidth=1;for(let i=1;i<7;i++){const y=i*h/7;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.beginPath();p.forEach((v,i)=>{const x=i*(w-8)/(p.length-1)+4,y=h-18-(v-min)/r*(h-35);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='#f4f6ff';ctx.lineWidth=2.3;ctx.stroke()}
function updateScales(){if(!state.prices.length)return;const p=state.prices.slice(-50),max=Math.max(...p),min=Math.min(...p),r=max-min||1;ui.scale1.textContent=fmt(max);ui.scale2.textContent=fmt(max-r*.33);ui.scale3.textContent=fmt(max-r*.66);ui.scale4.textContent=fmt(min)}
function onTick(t){const q=Number(t.quote);if(!Number.isFinite(q))return;const prev=state.prices.at(-1);state.prices.push(q);if(state.prices.length>120)state.prices.shift();const d=lastDigit(q);if(d!==null)state.digits[d]++;ui.price.textContent=fmt(q);ui.change.textContent=`${q>prev?'↑':'↓'} ${(prev?Math.abs((q-prev)/prev*100):0).toFixed(2)}%`;ui.tickCount.textContent=state.prices.length+' ticks';updateDigits();drawChart();updateScales();if(state.pending)settle(q)}
function loadHistory(prices){state.prices=prices.map(Number).filter(Number.isFinite).slice(-100);state.digits=Array(10).fill(0);state.prices.forEach(q=>{const d=lastDigit(q);if(d!==null)state.digits[d]++});updateDigits();drawChart();updateScales();if(state.prices.length)ui.price.textContent=fmt(state.prices.at(-1))}
function subscribe(){const ws=state.ws;if(!ws||ws.readyState!==WebSocket.OPEN)return;ws.send(JSON.stringify({ticks_history:state.symbol,count:100,end:'latest',style:'ticks',req_id:1}));ws.send(JSON.stringify({ticks:state.symbol,subscribe:1,req_id:2}))}
function connect(){clearTimeout(state.reconnect);setConn('Connecting…');const ws=new WebSocket('wss://ws.binaryws.com/websockets/v3');state.ws=ws;ws.onopen=()=>{setConn('Live market connected',true);subscribe()};ws.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.error){setConn('Deriv data error');console.warn(d.error);return}if(d.msg_type==='history'&&d.history?.prices)loadHistory(d.history.prices);if(d.msg_type==='tick'&&d.tick)onTick(d.tick)}catch(err){console.warn(err)}};ws.onerror=()=>setConn('Connection error');ws.onclose=()=>{setConn('Reconnecting…');state.reconnect=setTimeout(connect,2500)}}
function setStake(v){state.stake=Math.max(.25,Math.min(100,Math.round(v*100)/100));ui.stake.textContent=state.stake.toFixed(2)}
function setContract(c){state.contract=c;state.activeSide=null;state.pending=null;document.querySelectorAll('.contract-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.contract===c));updateActionButtons()}
function sides(){if(state.contract==='OVERUNDER')return ['OVER','UNDER'];if(state.contract==='MATCHES')return ['MATCH','DIFFERS'];return ['EVEN','ODD']}
function buttonForSide(side){return side==='EVEN'||side==='MATCH'||side==='OVER'?ui.even:ui.odd}
function updateActionButtons(){const [a,b]=sides();ui.even.innerHTML=`${a[0]+a.slice(1).toLowerCase()} <small>Payout 98.23%</small>`;ui.odd.innerHTML=`${b[0]+b.slice(1).toLowerCase()} <small>Payout 98.23%</small>`;ui.even.classList.remove('active-stop');ui.odd.classList.remove('active-stop');if(state.activeSide){const active=buttonForSide(state.activeSide);active.textContent='■ STOP';active.classList.add('active-stop')}}
function startTrade(side){if(state.activeSide){if(state.activeSide===side){stopTrading();}else toast('Stop the active trade first.');return}if(state.stopped){toast('Trading is stopped.');return}if(!state.prices.length){toast('Waiting for live market data.');return}if(state.balance<state.stake){toast('Demo balance is too low.');return}state.activeSide=side;state.lastSide=side==='ODD'||side==='UNDER'||side==='DIFFERS'?'right':'left';state.balance-=state.stake;state.pending={side,entry:state.prices.at(-1),stake:state.stake,contract:state.contract};updateActionButtons();toast(side+' demo trade started')}
function stopTrading(){state.activeSide=null;state.pending=null;updateActionButtons();toast('Trading stopped')}
function settle(q){const t=state.pending;if(!t)return;const d=lastDigit(q);let win=false;if(t.contract==='EVENODD')win=t.side==='EVEN'?d%2===0:d%2===1;else if(t.contract==='OVERUNDER')win=t.side==='OVER'?d>=5:d<=4;else win=t.side==='MATCH'?d===0:d!==0;const mult=Math.max(.01,Number(ui.mult.value)||2);const profit=win?t.stake*mult:t.stake;state.pending=null;state.tickSerial++;if(win){state.balance+=profit;state.net+=profit-state.stake;state.wins++}else{state.net-=state.stake;state.losses++}ui.net.textContent=(state.net>=0?'+$':'-$')+Math.abs(state.net).toFixed(2);ui.session.textContent=`${state.tickSerial} - ${state.wins}W - ${state.losses}L`;state.activeSide=null;updateActionButtons();checkLimits();toast(win?`WIN +$${(profit-state.stake).toFixed(2)}`:`LOSS -$${state.stake.toFixed(2)}`)}
function checkLimits(){const target=Number(ui.target.value)||0,sl=Number(ui.loss.value)||0;if(target&&state.net>=target)state.stopped=true;if(sl&&state.net<=-sl)state.stopped=true}
$('market').onchange=e=>{state.symbol=e.target.value;ui.marketName.textContent=e.target.options[e.target.selectedIndex].text;state.prices=[];state.digits=Array(10).fill(0);try{state.ws.close()}catch(_){}connect()};
document.querySelectorAll('.contract-tabs button').forEach(b=>b.onclick=()=>setContract(b.dataset.contract));
document.querySelectorAll('[data-delta]').forEach(b=>b.onclick=()=>setStake(state.stake+Number(b.dataset.delta)));
document.querySelectorAll('[data-stake]').forEach(b=>b.onclick=()=>setStake(Number(b.dataset.stake)));
ui.even.onclick=()=>startTrade(sides()[0]);ui.odd.onclick=()=>startTrade(sides()[1]);
$('autoMode').onclick=()=>{state.mode='AUTO';$('autoMode').classList.add('active');$('manualMode').classList.remove('active')};$('manualMode').onclick=()=>{state.mode='MANUAL';$('manualMode').classList.add('active');$('autoMode').classList.remove('active')};
window.addEventListener('resize',drawChart);setStake(.25);updateActionButtons();connect();
})();
